const FLAGS: Record<string, string> = {
  'México': '🇲🇽',
  'África do Sul': '🇿🇦',
  'Coreia do Sul': '🇰🇷',
  'República Tcheca': '🇨🇿',
  'Canadá': '🇨🇦',
  'Bósnia-Herzegovina': '🇧🇦',
  'Estados Unidos': '🇺🇸',
  'Paraguai': '🇵🇾',
  'Catar': '🇶🇦',
  'Suíça': '🇨🇭',
  'Brasil': '🇧🇷',
  'Marrocos': '🇲🇦',
  'Haiti': '🇭🇹',
  'Escócia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Austrália': '🇦🇺',
  'Turquia': '🇹🇷',
  'Alemanha': '🇩🇪',
  'Curaçao': '🇨🇼',
  'Holanda': '🇳🇱',
  'Japão': '🇯🇵',
  'Costa do Marfim': '🇨🇮',
  'Equador': '🇪🇨',
  'Suécia': '🇸🇪',
  'Tunísia': '🇹🇳',
  'Espanha': '🇪🇸',
  'Cabo Verde': '🇨🇻',
  'Bélgica': '🇧🇪',
  'Egito': '🇪🇬',
  'Arábia Saudita': '🇸🇦',
  'Uruguai': '🇺🇾',
  'Irã': '🇮🇷',
  'Nova Zelândia': '🇳🇿',
  'França': '🇫🇷',
  'Senegal': '🇸🇳',
  'Iraque': '🇮🇶',
  'Noruega': '🇳🇴',
  'Argentina': '🇦🇷',
  'Argélia': '🇩🇿',
  'Áustria': '🇦🇹',
  'Jordânia': '🇯🇴',
  'Portugal': '🇵🇹',
  'Congo': '🇨🇩',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Croácia': '🇭🇷',
  'Gana': '🇬🇭',
  'Panamá': '🇵🇦',
  'Uzbequistão': '🇺🇿',
  'Colômbia': '🇨🇴',
}

export function teamFlag(name: string): string {
  return FLAGS[name] ?? '🏳️'
}
