/** Códigos ISO → arquivos em public/flags/ (Inglaterra/Escócia: gb-eng, gb-sct). */
const TEAM_CODES: Record<string, string> = {
  'México': 'mx',
  'África do Sul': 'za',
  'Coreia do Sul': 'kr',
  'República Tcheca': 'cz',
  'Canadá': 'ca',
  'Bósnia-Herzegovina': 'ba',
  'Estados Unidos': 'us',
  'Paraguai': 'py',
  'Catar': 'qa',
  'Suíça': 'ch',
  'Brasil': 'br',
  'Marrocos': 'ma',
  'Haiti': 'ht',
  'Escócia': 'gb-sct',
  'Austrália': 'au',
  'Turquia': 'tr',
  'Alemanha': 'de',
  'Curaçao': 'cw',
  'Holanda': 'nl',
  'Japão': 'jp',
  'Costa do Marfim': 'ci',
  'Equador': 'ec',
  'Suécia': 'se',
  'Tunísia': 'tn',
  'Espanha': 'es',
  'Cabo Verde': 'cv',
  'Bélgica': 'be',
  'Egito': 'eg',
  'Arábia Saudita': 'sa',
  'Uruguai': 'uy',
  'Irã': 'ir',
  'Nova Zelândia': 'nz',
  'França': 'fr',
  'Senegal': 'sn',
  'Iraque': 'iq',
  'Noruega': 'no',
  'Argentina': 'ar',
  'Argélia': 'dz',
  'Áustria': 'at',
  'Jordânia': 'jo',
  'Portugal': 'pt',
  'Congo': 'cd',
  'Inglaterra': 'gb-eng',
  'Croácia': 'hr',
  'Gana': 'gh',
  'Panamá': 'pa',
  'Uzbequistão': 'uz',
  'Colômbia': 'co',
}

const TEAM_EMOJI: Record<string, string> = {
  'México': '🇲🇽',
  'África do Sul': '🇿🇦',
  'Coreia do Sul': '🇰🇷',
  'República Tcheca': '🇨🇿',
  'Canadá': '🇨🇦',
  'Bósnia-Herzegovina': '🇧🇦',
  'Estados Unidos': '🇺🇸',
  'Paraguai': '🇵🇾',
  'Catar': '🇶🇦',
  'Suíça': '🇨🇭',
  'Brasil': '🇧🇷',
  'Marrocos': '🇲🇦',
  'Haiti': '🇭🇹',
  'Escócia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Austrália': '🇦🇺',
  'Turquia': '🇹🇷',
  'Alemanha': '🇩🇪',
  'Curaçao': '🇨🇼',
  'Holanda': '🇳🇱',
  'Japão': '🇯🇵',
  'Costa do Marfim': '🇨🇮',
  'Equador': '🇪🇨',
  'Suécia': '🇸🇪',
  'Tunísia': '🇹🇳',
  'Espanha': '🇪🇸',
  'Cabo Verde': '🇨🇻',
  'Bélgica': '🇧🇪',
  'Egito': '🇪🇬',
  'Arábia Saudita': '🇸🇦',
  'Uruguai': '🇺🇾',
  'Irã': '🇮🇷',
  'Nova Zelândia': '🇳🇿',
  'França': '🇫🇷',
  'Senegal': '🇸🇳',
  'Iraque': '🇮🇶',
  'Noruega': '🇳🇴',
  'Argentina': '🇦🇷',
  'Argélia': '🇩🇿',
  'Áustria': '🇦🇹',
  'Jordânia': '🇯🇴',
  'Portugal': '🇵🇹',
  'Congo': '🇨🇩',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Croácia': '🇭🇷',
  'Gana': '🇬🇭',
  'Panamá': '🇵🇦',
  'Uzbequistão': '🇺🇿',
  'Colômbia': '🇨🇴',
}

/** Siglas FIFA (3 letras) para versões compactas (bracket). */
const TEAM_ABBR: Record<string, string> = {
  'México': 'MEX',
  'África do Sul': 'RSA',
  'Coreia do Sul': 'KOR',
  'República Tcheca': 'CZE',
  'Canadá': 'CAN',
  'Bósnia-Herzegovina': 'BIH',
  'Estados Unidos': 'USA',
  'Paraguai': 'PAR',
  'Catar': 'QAT',
  'Suíça': 'SUI',
  'Brasil': 'BRA',
  'Marrocos': 'MAR',
  'Haiti': 'HAI',
  'Escócia': 'SCO',
  'Austrália': 'AUS',
  'Turquia': 'TUR',
  'Alemanha': 'GER',
  'Curaçao': 'CUW',
  'Holanda': 'NED',
  'Japão': 'JPN',
  'Costa do Marfim': 'CIV',
  'Equador': 'ECU',
  'Suécia': 'SWE',
  'Tunísia': 'TUN',
  'Espanha': 'ESP',
  'Cabo Verde': 'CPV',
  'Bélgica': 'BEL',
  'Egito': 'EGY',
  'Arábia Saudita': 'KSA',
  'Uruguai': 'URU',
  'Irã': 'IRN',
  'Nova Zelândia': 'NZL',
  'França': 'FRA',
  'Senegal': 'SEN',
  'Iraque': 'IRQ',
  'Noruega': 'NOR',
  'Argentina': 'ARG',
  'Argélia': 'ALG',
  'Áustria': 'AUT',
  'Jordânia': 'JOR',
  'Portugal': 'POR',
  'Congo': 'COD',
  'Inglaterra': 'ENG',
  'Croácia': 'CRO',
  'Gana': 'GHA',
  'Panamá': 'PAN',
  'Uzbequistão': 'UZB',
  'Colômbia': 'COL',
}

const DEFAULT_CODE = 'xx'

export function teamFlagCode(name: string): string {
  return TEAM_CODES[name] ?? DEFAULT_CODE
}

/** Sigla de 3 letras; cai para as 3 primeiras letras maiúsculas se desconhecida. */
export function teamAbbr(name: string): string {
  return TEAM_ABBR[name] ?? name.slice(0, 3).toUpperCase()
}

/** Bandeira hospedada no app (public/flags) — funciona em Mac, Windows e no SVG do gráfico. */
export function teamFlagUrl(name: string): string {
  return `${import.meta.env.BASE_URL}flags/${teamFlagCode(name)}.png`
}

/** Fallback visual quando a imagem não carrega (ex.: time novo sem PNG). */
export function teamFlagEmoji(name: string): string {
  return TEAM_EMOJI[name] ?? '🏳️'
}
